### ISSUE TITLE
Data collection: ICU beds

### ISSUE THREAD

**Issue by fkrauer** [schoolofdata-ch/swiss-hospital-data#5]
We need someone to digitize the data on ICU beds from here:

https://www.swiss-icu-cert.ch/files/daten/Dokumente/liste_zertifizierte/Internet_Liste_SGI_zertifizierte_Intensivstationen_200311.01.pd

**Comment by magdasalatka** [comment]
Hi @fkrauer,

it looks like the link is invalid

**Comment by Taremeh** [comment]
> Hi @fkrauer,
> 
> it looks like the link is invalid

https://www.swiss-icu-cert.ch/files/daten/Dokumente/liste_zertifizierte/Internet_Liste_SGI_zertifizierte_Intensivstationen_200311.01.pdf

The `f` of `.pdf` was missing :)

(btw. since the table has been digitized, I'll close the issue)
